import ChurchTribute from '../assets/church_tribute.jpg';

const Tributes = [
    {
        title: "Tribute to my Wife, Mrs Edna Edeh.",
        tribute: "Chi (as I fondly call you), I lack words to express what I am going through right now. Loosing you has made me realize how empty this life is, but in all things we give thanks to God. \n\nI had hoped you will beat the ill health this time as you had always done, but I was wrong. \n\nYou were my support at my lowest moment in life, you were there for me and the entire family and ensured we never lacked anything you could provide. \n\nThank God for bringing you my way and blessing me with your presence these past years.\n\nContinue to rest in God's bossom. \n\nPastor Chidi Isaiah Edeh"
    },
    {
        title: "Tribute to my Dear Mother, Mrs Edna Amarachukwu Chioma Edeh",
        tribute: "Mama or Moi, as I fondly call you, it is difficult to address you using past tenses. It is even more difficult for me to agree with the reality that you have passed on to eternal glory. However, I take solace in the undisputable fact that you are in heaven resting with the saints. \n\nI have had time to cry, wail, ask questions without being answered and have come to terms with the fact that not being able to speak with you every morning, receive blessings from you for me and my family is now the new normal. \n\nIt breaks my heart when I remember that after all the sacrifices you made to ensure we received good education and were well taken care of, you transited even before we could appreciate you enough. However, I am consoled by the fact that we did the best we could when you were with us.  \n\nThe hard times you went through and the way God led you through them till you took your last breath are a testament to the fact that you had a personal relationship with God. Particularly, I remember that twice (in the mid 90s), your doctors gave you 2 weeks and 3 months respectively to live, but God made sure they were wrong. I also remember that on 3rd December 1993 you survived an attack by 4 men who attempted to kill and use you for rituals. On that day God himself rescued you from them. These are just a few of the several near death experiences you had and in all, God kept you, and for a purpose. \n\nThe memories we made while you were with us will always be a consolation to me now that you are no more. \n\nMoi, what won't I give to see you smile at me one more time, to receive my daily blessings in the morning when I call you, to hear your voice speak to or scold me one more time, to assure me that the difficult times will soon be over, to advice me before I make a critical decision, to tell me stories about your childhood and how you took care of the elderly women in your community as a little girl...., God knows why it had to be now. \n\nIn all, I accept and submit to God's timing because he was the one who kept you till 18th March 2025. \n\nYour husband, children, grand children, brother & sister, nephews, neices, friends, associates and other family members will miss you. \n\nJee nke oma, Nne m oma. Jee nke oma, mama Chinazo \nYour son, Chinazo"
    },
    {
        title: "A Tribute to my mother.",
        tribute: "Moi as we fondly call you, you were a back bone not just to me and my family but to a lot of other people. You were full of love, wisdom,  my greatest teacher and my source of inspiration. Above all you were a devout Christian and you made use of every opportunity you had to preach the word of God and to encourage people. \n\nYou sacrificed a lot just for us (your children) and a lot of other people to be comfortable even at the expense of your own comfort. You taught me the importance of hard work and honesty. You were kind and loving. You were my confidant and my biggest supporter. \n\nNne m, you were courageous, resilient, God fearing and you lived an impactful life. Your life was a testament of love, faith and strength. The void your departure to eternal glory has created in my heart can never be filled by anyone else but I find comfort knowing that your love will guide me always. I miss you so dearly, nnem, but I promise that you will forever be in my heart. \n\nJe nke oma nnem. \n\nChiziterem. (Ada gi)."
    },
    {
        title: "To my dear mum, Ezinne m.",
        tribute: "Your untimely death and glorious exit from this world has brought a lot of questions to my mind. Your undeserving death made me to think of the journey you took us your children through. Your life to us as a family was all about sacrifice. Your role to us as a mother was beyond motherly care but that of a sacrificial lamb who gave her all to see that her family stands tall. \n\nOh Ezinne m, It was because of you that we survived...Dear mum we'll forever miss you. We have this confidence that it is heaven's gain for you to Even though I cry in each passing day cause  it's been long I saw you. Today I glory in your faith in CHRIST JESUS which was undiluted. Today I flourish in your streams of prayers for us, cause I know that you've joined the HOSTS OF HEAVEN. \n\nChaii Ezinne m, It is with heavy heart of sorrow and grief I wish to bid you farewell not as of those who do not have hope, cause I know we will meet at the resurrection morning when the trumpet shall sound and the dead in CHRIST will rise. \n\nNne m Jee Nkeoma \nEzinne m Your dreams lives on.\n\nChukwunonyerem Edeh Jnr"
    },
    {
        title: "Tribute to a mother general. Mrs EDNA EDE (CNO Rtd)",
        tribute: "My senior colleague, my mentor and a mother to my entire family at Independence layout. Aunty Senior as you were fondly called by my children. It is rather unfortunate that we got to hear of your demise like an evening news that turned out to be real. I missed your peaceful voice that use to call me nne -bekee when I entered your home, I now realized you have actually gone to be with your creator. God said in everything we should thank him . Praise God. \n\nYou lived an impactful life. God bless your soul for us in Jesus name. Your home was an extension of my family. Your motherly support in every aspect was overwhelming . During the period my children were small and our Daddy travelled  to Lagos for a program . I didn't have challenge with where to keep them when on night shift. Your food basket extended to my family. \n\nYou and Daddy will even come around to check on us. Chaii distance became a barrier when we packed out from Independence layout. We planned a visit last year but my health challenge  delayed it and early this year and we couldn't make it and we're still planning to actualize it when suddenly this sad news came. The world is a mysterious place indeed. \n\nI pray to God Almighty to give the family you left behind, the fortitude to bear your relocation above. \n\nMay your gentle and loving soul continue to rest in perfect peace in Jesus name. \n\nNnenna Eke Agwu (Rtd Nurse UNTH.) \non behalf of my family."
    },
    {
        title: "Tribute To my Dearest Edna",
        tribute: "Life is indeed a phase. Nnem I was with you this January, We discussed so many things but you never gave me any sign that I was seeing you for the last time. Less than 3 months afterwards, I heard a different story. Life is indeed a phase. \n\nRest peacefully ma! \nFarewell taatam! \n\nJohnny Nwanne"
    },
    {
        title: "Tribute to Big Auntie Edna Edeh",
        tribute: "Nwagboho! Sweet Sixteen! As we all fondly called you...\n\nIt's been very difficult coming to terms with the current reality that you have left us for heaven.But we are painfully comforted with the truth of scriptures that the death of the righteous is God taking the person away from the evil to come into peace and rest - Isa 57:1-2. You lived a worthy life - raising a family in the fear of the Lord while loving and serving your Master Jesus until the very end. Precious in the sight of the Lord is the death of His saints - Ps 116:15. \n\nGood night Big Auntie. Tears are not enough! \n\nThe Heritage of \nElder S.S. & Helen Nwanne of blessed memory. \nNdibnuhu, Abueke"
    },
    {
        title: "A Tribute to a Godly mother.",
        tribute: "O mummy ooo! My beloved sister and mother, My prayer warrior,  my bosom friend who believes that immediately we met together in prayer God will show us His will in life. I was told that you were sick and admitted in the hospital and I told you that I will pray which I did. I later came to see you and you were  very happy and after prayers  you instructed me to go and close my fasting in your bedroom. You told me that you have finished  climbing a very big miuntain. I did not know that it was my last fellowship  with you.\n\n Oh what can I say. The word of God says in Matt. 5:4  that  blessed are those that mourn for they shall be comforted. I know you are in the blossom of the Lord where we shall meet  to part no more in Jesus Mighty name. Amen. It is well with your soul.  \n\nMummy Akobundu (Nweze)."
    },
    {
        title: "A Tribute to a woman of God.",
        tribute: "Mummy Edna Edeh, a pillar of strength, love, and faith. Your selfless dedication to family, community, and faith has touched countless lives. May your legacy of love, kindness, and devotion inspire future generations. \n\nEngr and mrs Gabriel Emmanuel"
    },
    {
        title: "A TRIBUTE TO MRS. EDNA EDEH BY EVANGELIST. MRS OLUCHI EZURIKE.",
        tribute: "Life at best is very short and brief. Sister Edna as I fondly called her was a daughter of Zion, a Pastor's wife and a Nurse of high reputation in a government hospital. I met her in the circle of believers always beaming with a smile.  She was so humble. Her Godly marriage life was a food for thought and should be studied by the younger generation.Good bye as you are being buried to mother earth today. May GOD ALMIGHTY continue to rest your soul in peace."
    },
    {
        title: "Tribute to Mummy Edna Edeh one of our Ministry Supporters",
        tribute: "How do I start writing my final tribute to a woman and member who has not just treated me like a pastor alone, but as a son and confident. Mummy Edna, you were not just my member, you were more than a member to me and the family. You were indeed a mother, a ministry supporter and you shared so many revelation, we saw come through together, (in fact your monthly support for the family was also a great booster for the drugs of this children and you never missed it). \n\nMummy Edna, you servedd God faithfully to the best of my knowledge, you were passionate in doing God's work. You gave your advice, financial support and did all you could, for the progress of the Kingdom. \n\nYour death came with great pain for me and the family, not just for your monthly support to the family and contribution to the church, but also because your death was the first to break the Covenant of Life we shared as a church. I remember less than 30 minutes before I got the news of your departure, I reminded you of that covenant. Because, I know, it is possible for you to come out of that state of curmma. For I have heard, seen and experience God placed your life in the past. \n\nHowever, to God, your death is an act that happens in accordance with His sovereign will and nature. Life and death are in His hands. Whatever He allows to happen. He does it based on His perfect knowledge and will. Mummy Edna, we miss you greatly, the church also misses you. \n\nSleep well, till that resurrection morning. \n\nRev. Nnanna G.U"
    },
    {
        title: "A TRIBUTE TO OUR BIG  MUMMY",
        tribute: "It is difficult to come to terms that you're gone. l thought that I will wake up from the dream. You were a kind hearted woman, a prayer warrior, a counselor, a supporter of God's work, we will miss your motherly advice. May your soul find perfect rest on the Bosom of our Lord Jesus Christ Amen.we are console with what the song writer in SS&S 607 stanza 4. \"THERE DEPTHS OF LOVE THAT I CANNOT KNOW TILL I CROSS THE NARROW SEA, THERE ARE HIGHTS OF JOY THAT I MAY NOT REACH TILL I REST IN PEACE WITH THEE.\"GOD Take Charge,Heal Every Broken Heart and Spirit. By your Grace grant our Mummy a Peaceful Rest. May God grant the Family, the church of God the fortitude to bear  this Great lose. Holy Father you remain the Unquestionable God. \n\nAdieu Our Big Mummy, Adieu Mummy Edna, Good Night until that Beautiful resurrection morning. \n\nElder & Mrs Onyenonachi Sunday."
    },
    {
        title: "TRIBUTE TO A MOTHER IN WHOM THERE WAS NO GUILE!!!",
        tribute: "Death do not rejoice for succeeding with my Mummy and God’s general. You have only enabled her to transcend to a better place. My heart is aching sooo much Mummy over your demise. We chatted on Saturday and on Tuesday you took your eternal flight to heaven. A great prophet of our time, a prayer warrior, an encourager, a kindhearted and very caring Mummy, a true model of what a mother should be. \n\nYou were such a great asset that I always looked forward to either seeing you in fellowship or in church because your smile always rolled away every fear, I had concerning life. You loved my husband like a son and at his death, you extended that love to me. It was because of your attachment to him that the Lord graciously revealed to you that he would go home to be with the Lord at the time he did. Mummy, you were one of the people whose words enabled me to accept God’s verdict about my widowhood at the time it came. \n\nIt was what I saw in you that actually fueled my deep passion for close walk with God This is because you will always call to ask me ...Clara is God taking care of you like He promised me at your husband’s death that he would…. I would of course always answer in the affirmative and you will joyfully tell me that it was the Lord that sent you to ask me that question. The drama was as puzzling as it was exciting to me! It actually made me crave for such intimacy with the Lord and which He has by His grace availed me. \n\nYour death came as a big shoch to me and several others and I am yet to recover from it, as I never ever contemplated that the end will come so soon. \n\nMummy, in you there was no guile and that greatly endeared you to me. You lived an unpretentious life that made you quite exceptional.  I learnt to have an unshakeable faith in the Lord through you. Yours was a life lived in total obedience to the Lord. Mummy the quintessential giant!!! What I have now are only beautiful memories of the times I shared with you in fellowship and otherwise. \n\nI will forever hold those memories dear to my heart till we meet again on that resurrection morning. I bless God for the privilege of knowing you, loving you and sharing deep fellowship with you here on earth. You remain unforgettable!!! Mummy’m, the beautiful one, keep resting in power till we meet again in that glory land!!! Always in my heart!!! \n\nSis Clara Obi-Ochiabutor"
    },
    {
        title: "ECWA II/TRANS-EKULU WOMEN FELLOWSHIP TRIBUTE",
        tribute: "Dear mummy, your passing was a great shock to us when we least expected. We miss your advice and motherly love in the fellowship. You left a vacuum that can hardly be filled. We miss you, but are comforted that you are in a better place. \n\nGod be with you till we meet again."
    },
    {
        title: "Tribute to a woman of Grace",
        tribute: "She was a woman of grace. She had a heart full of love. We will miss her smiles, love, and heart full of love. May her lovely soul Rest in peace. \n\nChuchu & family"
    },
    {
        title: "Tribute to a great woman of God!",
        tribute: "A saint has gone to be with the Lord. Mummy, you were the mother general. A mentor, a generous woman. Your generosity knew no bounds. You could never ignore any one crying for help. You always extended a helping hand, not minding whether you knew them or not. \n\nYou made me what I am today in Christendom. You made me draw closer to God, to worship Him both in spirit and truth. I will never forget the role you played, and the impact it had on my family as a whole, from when my Late husband was alive, till the time of your death. \n\nMummy, you were so intimate with the word, that even hidden things were revealed to you. So much so, that you had conversations with the Lord, just as Moses of old had with Him. I find it difficult to accept that you’re no more, mummy! \n\nI really miss you, and lack words to begin to narrate what you did for myself, and my family. \n\nContinue to rest in the bosom of the Lord, till we meet at the resurrection morning to part no more. \n\nMrs. Esther Okehie & Family."
    },
    {
        title: "Tribute to Mummy Edna",
        tribute: "You may have passed on, but your memories will always live on within us. Thank you for your sacrifices, care, concern, love, and everything you have done for me, and my family. You provided us with shelter when we hadn’t a place to live. I will be forever grateful and thankful to you. I know you’re in a better place, in the bosom of the Lord. \n\nAdieu Ezinne, \nAdieu my co-wife, \nAdieu nwanyi oma. \n\nYour co-wife, \nEbeh Blessing Chinyere. \n(Mama Ebube)."
    },
    {
        title: "TRIBUTE TO BELOVED SISTER ",
        tribute: "De Adam Babe Abakaliki is asking, Is it how u just disappeared in this world.oh my sister that has a good sisters love,my sister that is caring and take care of her children.The last discussion we had was how prepare for the burial of  our elder sister but death come knocking at ur door.oh dead why? Why my dear sister Since I had of ur death is still as a shock to me but we can't question God. cus he knows all.Babe Abakaliki is saying farewell  to u my belove sister. Farewell De Adam Edna!! May God grant you Eternal rest in heaven. \n\nMr And Mrs Roseline Akpanaka \nThe younger Sister."
    },
    {
        title: "Tribute to Late. Mrs. Edna Edeh.",
        tribute: "A woman of honour and impeccable love for GOD and humanity. \n\nOur paths crossed with the unique family of Rev. Chidi Edeh ( Rtd) at Evangelical Church Winning All (ECWA 2) Abakpa Enugu in 2002, when I was serving as Court of Appeal justice at Enugu Division. Lady Edna Edeh, and her husband showed me great love of Jesus Christ and they were of great assistance to me in settling down in the entirely new environment. \n\nHerself and the family epitomised, the character and attribute of Jesus Christ in all ramifications. Our relationship has endured the test of time. We have indeed lost a rare gem. Our consolation is that we will meet at the feet of Jesus at the end of age. \n\nMay the Lord comfort the family and the church, and give us  all fortitude to bear the great loss. Amen. \n\nHon. Justice. Clara Bata Ogunbiyi Jsc(Rtd) CFR."
    },
    {
        title: "Tribute To A Loving Mum!",
        tribute: "Losing Mommy is like losing a piece of my childhood. I will always remember you from our time at the Church. You were just a face in the church crowd; you were a beacon of warmth and kindness. Your gentle spirit and loving presence left an imprint on my heart that has lasted all these years. I left Enugu long ago, but the memories of you have never faded. I can still recall the comfort your presence brought, a feeling of being seen and cared for. Your legacy is one of pure love and grace, and I am so grateful to have known you.\n\nRest on Mommy! \nWith a heavy heart, \n\nOkpara Chinweuba Solomon"
    },
    {
        title: "",
        tribute: "",
        image: <img src={ChurchTribute} alt="" className='w-full h-auto lg:w-[55vh] lg:h-[75vh]' />
    },
    
]

export default Tributes;